(dp1
S'output'
p2
S'<type \'exceptions.SyntaxError\'> Field: invalid table name: master-table, use rname for "funny" names'
p3
sS'layer'
p4
S'C:\\Users\\Kim Son\\Documents\\Visualizr\\applications\\Visualizr\\models\\tables.py'
p5
sS'code'
p6
S'# -*- coding: utf-8 -*-\n\nimport os\n\n"""def retrieve_file(filename, path=None):\n    path = "applications/Visualizr/static"\n    return (filename, open(os.path.join(path, filename), \'rb\'))"""\n\ndb.define_table(\'master-table\',\n             Field(\'person\'),\n             Field(\'upload_data\', \'upload\', uploadfolder=os.path.join(request.folder, \'static\')),\n             Field(\'table_id\'))\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "C:\\Users\\Kim Son\\Documents\\Visualizr\\gluon\\restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "C:\\Users\\Kim Son\\Documents\\Visualizr\\applications\\Visualizr\\models\\tables.py", line 12, in <module>\n    Field(\'table_id\'))\n  File "C:\\Users\\Kim Son\\Documents\\Visualizr\\gluon\\packages\\dal\\pydal\\base.py", line 834, in define_table\n    table = self.lazy_define_table(tablename,*fields,**args)\n  File "C:\\Users\\Kim Son\\Documents\\Visualizr\\gluon\\packages\\dal\\pydal\\base.py", line 851, in lazy_define_table\n    table = table_class(self, tablename, *fields, **args)\n  File "C:\\Users\\Kim Son\\Documents\\Visualizr\\gluon\\packages\\dal\\pydal\\objects.py", line 226, in __init__\n    \'use rname for "funny" names\' % tablename)\nSyntaxError: Field: invalid table name: master-table, use rname for "funny" names\n'
p11
s.